### ISSUE TITLE
I would like to know where you managed to get the files from the /habbo-imaging/resources

### ISSUE THREAD

**Issue by salomaosnff** [dank074/arcturus-tools#1]
Hello, very interesting your project!
I would like to know where you managed to get the files from the /habbo-imaging/resources

**Comment by dank074** [comment]
I have created the following utility for extracting the images and manifest files from the swf files:
[https://github.com/dank074/SpriteExtractor/releases/tag/1.0](https://github.com/dank074/SpriteExtractor/releases/tag/1.0)

You would just run the above java program with the options to extract clothes sprites or effects sprites as appropiate. Then you would move the following outputs to their respective path in resources:
 `/output/clothes/sprites`  -> `resources/avatar`
 `/output/clothes/manifest` -> `resources/xml/assets`

`/output/effects/sprites` -> `resources/avatar`
`/output/effects/manifest` -> `resources/xml/fx`
